on:
  rss:
    url: https://breakingnewsenglish.com/bne.xml
    config:
      timeZone: UTC
      every: "30 22 * * *"
      limit: 1
jobs:
  telegram:
    name: Send a telegram message
    runs-on: ubuntu-latest
    steps:
      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: 786143398
          token: 1748509976:AAF_dKwGcPRt7wToKrG2AakaB1T8T9_J0pw
          message: |
            ${{on.rss.outputs.title}}
            ${{on.rss.outputs.link}}
          format: markdown
